---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  require_ansible_repo: false
  require_ansible_omnibus: true
  requirements_path: requirements.yml
  extra_vars: 
    java_packages: ['java-1.8.0-openjdk']

platforms:
  - name: centos-7.2

suites:
  - name: default
